export const DATOS = [
  {
    id: "ACC-001",
    title: "Mini UPS DC",
    colection: "accesorio",
    valery_name: "Mini UPS 20000MaH",
    description:
      "• Capacidad: 20.000 mAh de alta duración. \n• Compatibilidad: Routers, Antenas POE, Cámaras de seguridad y dispositivos de red.\n• Salidas DC: 5V / 9V / 12V seleccionables.\n• Puerto POE: 15V / 24V para antenas y equipos específicos.\n• Indicadores: LEDs de estado de carga y encendido.\n",
    availability: "in stock",
    condition: "new",
    price: 23,
    link: "https://wa.me/584129230341?text=Hola%20Compucentro,%20me%20interesa%20el%20producto%20ID:%20ACC-001%20-%20Mini UPS DC",
    image_link:
      "https://raw.githubusercontent.com/KDR-2/compucentro-img/main/ACC-001.webp",
    additional_image_link: "",
    brand: "Olax",
    google_product_category:
      "Electronics > Networking > Network Hubs & Switches",
    product_type: "Accesorios > Energía",
    availability_circle_origin: "",
  },
  {
    id: "ACC-002",
    title: "Funda Protectora para Laptops",
    colection: "accesorio",
    valery_name: "Forro Laptop UP",
    description:
      'Funda Protectora U-products para Laptop 14"\n\nProtección esencial contra rayones, polvo y golpes leves. Diseño ligero y resistente.\n\n• Compatibilidad: Laptops y Tablets hasta 14 pulgadas. \n• Material: Neopreno / Tela acolchada de alta densidad. \n• Marca: U-products. \n• Uso: Ideal para morrales o transporte individual.\n\nOfrecemos precio al mayor disponible en divisas',
    availability: "in stock",
    condition: "new",
    price: 7.5,
    link: "https://wa.me/584129230341?text=Hola%20Compucentro,%20me%20interesa%20el%20producto%20ID:%20ACC-002%20-%20Funda Protectora para Laptops",
    image_link:
      "https://raw.githubusercontent.com/KDR-2/compucentro-img/main/ACC-002.webp",
    additional_image_link: "",
    brand: "U-products",
    google_product_category: "Electronics > Laptop Accessories > Laptop Cases",
    product_type: "Accesorios > Protección",
    availability_circle_origin: "",
  },
  {
    id: "ACC-003",
    title: "Mouse Pad Antideslizante",
    colection: "accesorio",
    valery_name: "Mouse Pad",
    description:
      "Mouse Pad Antideslizante\n\nSuperficie de tela optimizada para alta precisión y base de goma para mayor estabilidad. Ideal para oficina, estudio o gaming ligero.\n\n• Colores disponibles: Azul y Rosado. \n• Superficie: Microfibra de baja fricción. \n• Base: Goma antideslizante de alta adherencia. \n• Compatibilidad: Todo tipo de mouses (Ópticos y Láser).\n\n❕ Ofrecemos precio al mayor disponible en divisas.",
    availability: "in stock",
    condition: "new",
    price: 4.5,
    link: "https://wa.me/584129230341?text=Hola%20Compucentro,%20me%20interesa%20el%20producto%20ID:%20ACC-003%20-%20Mouse Pad Antideslizante",
    image_link:
      "https://raw.githubusercontent.com/KDR-2/compucentro-img/main/ACC-003.webp",
    additional_image_link:
      "https://raw.githubusercontent.com/KDR-2/compucentro-img/main/ACC-003-2.webp",
    brand: "Genérico",
    google_product_category:
      "Electronics > Print, Copy, Scan & Fax > Mouse Pads",
    product_type: "Accesorios > Oficina",
    availability_circle_origin: "",
  },
  {
    id: "ACC-004",
    title: "Audifonos Gamer Hylas",
    colection: "accesorio",
    valery_name: "Audifonos Gamer Hylas",
    description:
      "Headset Gamer Hylas - Sonido Envolvente con Micrófono\n\nAuriculares cableados de alto rendimiento diseñados para largas sesiones de juego. Comodidad superior y claridad de audio para gaming y streaming.\n\n• Micrófono: Omnidireccional con cancelación de ruido básica. • Ajuste: Diadema ligera y ajustable con almohadillas acolchadas. • Conexión: Cable reforzado para mínima latencia. • Compatibilidad: PC, Laptops y consolas (según conector). • Diseño: Ergonómico para reducción de fatiga auditiva.\n\n❕ Ofrecemos precio al mayor disponible en divisas.",
    availability: "in stock",
    condition: "new",
    price: 37.5,
    link: "https://wa.me/584129230341?text=Hola%20Compucentro,%20me%20interesa%20el%20producto%20ID:%20ACC-004%20-%20Audifonos Gamer Hylas",
    image_link:
      "https://raw.githubusercontent.com/KDR-2/compucentro-img/main/ACC-004.webp",
    additional_image_link: "",
    brand: "Hylas",
    google_product_category:
      "Electronics > Audio > Audio Components > Headphones & Headsets",
    product_type: "Accesorios > Gaming",
    availability_circle_origin: "",
  },
  {
    id: "ACC-005",
    title: "Webcam Redragon",
    colection: "accesorio",
    valery_name: "WEBCAM REDRAGON 720P",
    description:
      "Webcam Redragon HD 720p - Ideal para Streaming y Oficina\n\nCámara web de alta definición con enfoque optimizado para videollamadas, clases virtuales y transmisiones en vivo. Plug & Play: conectar y usar.\n\n• Resolución: HD 720p real para imagen clara y fluida. \n• Compatibilidad: Total con Windows/Mac en Laptops y PCs. \n• Micrófono: Integrado con reducción de ruido ambiental. \n• Uso: Perfecta para Zoom, Google Meet, Skype y OBS Studio. \n• Soporte: Clip universal ajustable para monitores y pantallas de laptop.\n\n❕ Ofrecemos precio al mayor disponible en divisas.",
    availability: "in stock",
    condition: "new",
    price: 45,
    link: "https://wa.me/584129230341?text=Hola%20Compucentro,%20me%20interesa%20el%20producto%20ID:%20ACC-005%20-%20Webcam Redragon",
    image_link:
      "https://raw.githubusercontent.com/KDR-2/compucentro-img/main/ACC-005.webp",
    additional_image_link: "",
    brand: "Redragon",
    google_product_category:
      "Electronics > Video > Video Cameras > Computer Cameras",
    product_type: "Accesorios > Streaming",
    availability_circle_origin: "",
  },
  {
    id: "CPU-I7-8G-T",
    title: "CPU Tiny i7 8va Gen",
    colection: "cpu tiny",
    valery_name: "CPU i7 8va Gen 8RAM 256SSD TINY",
    description:
      "• Rendimiento i7 de alto nivel en formato ultra compacto. • Almacenamiento SSD de alta velocidad para respuesta inmediata. • Ideal para multitarea pesada y oficina moderna.",
    availability: "in stock",
    condition: "refurbished",
    price: 345,
    link: "https://wa.me/584129230341?text=Hola%20Compucentro,%20me%20interesa%20el%20producto%20ID:%20CPU-I7-8G-T%20-%20CPU Tiny i7 8va Gen",
    image_link:
      "https://raw.githubusercontent.com/KDR-2/compucentro-img/main/CPU-I7-8G-T.webp",
    additional_image_link: "",
    brand: "HP / Dell / Lenovo",
    google_product_category: 222,
    product_type:
      "Computadoras > Desktops > Tiny > i7 > 8va Gen > 8GB RAM > 256GB SSD",
    availability_circle_origin: "",
  },
  {
    id: "CPU-I7-7G-T",
    title: "CPU Tiny Intel Core i7 7ma Gen (8GB RAM / 256GB SSD)",
    colection: "cpu tiny",
    valery_name: "CPU i7 7ma Gen 8RAM 256SSD TINY",
    description:
      "• Potencia y eficiencia en tamaño miniatura. • Disco sólido SSD que garantiza fluidez en Windows 10/11. • Ahorro máximo de espacio en escritorio.",
    availability: "in stock",
    condition: "refurbished",
    price: 285,
    link: "https://wa.me/584129230341?text=Hola%20Compucentro,%20me%20interesa%20el%20producto%20ID:%20CPU-I7-7G-T%20-%20CPU Tiny Intel Core i7 7ma Gen (8GB RAM / 256GB SSD)",
    image_link:
      "https://raw.githubusercontent.com/KDR-2/compucentro-img/main/CPU-I7-7G-T.webp",
    additional_image_link: "",
    brand: "HP / Dell / Lenovo",
    google_product_category: 222,
    product_type:
      "Computadoras > Desktops > Tiny > i7 > 7ma Gen > 8GB RAM > 256GB SSD",
    availability_circle_origin: "",
  },
  {
    id: "CPU-I7-7G-T-2V",
    title: "CPU Tiny Intel Core i7 7ma Gen (8GB RAM / 256GB SSD / 2GB Video)",
    colection: "cpu tiny",
    valery_name: "CPU i7 7ma Gen 8RAM 256SSD 2TV TINY",
    description:
      "• Edición Especial con 2GB de Video Dedicado. • Ideal para diseño gráfico ligero o múltiples monitores. • Procesamiento i7 con SSD de alta velocidad.",
    availability: "in stock",
    condition: "refurbished",
    price: 322.5,
    link: "https://wa.me/584129230341?text=Hola%20Compucentro,%20me%20interesa%20el%20producto%20ID:%20CPU-I7-7G-T-2V%20-%20CPU Tiny Intel Core i7 7ma Gen (8GB RAM / 256GB SSD / 2GB Video)",
    image_link:
      "https://raw.githubusercontent.com/KDR-2/compucentro-img/main/CPU-I7-7G-T-2V.webp",
    additional_image_link: "",
    brand: "HP / Dell / Lenovo",
    google_product_category: 222,
    product_type:
      "Computadoras > Desktops > Tiny > i7 > 7ma Gen > 8GB RAM > 256GB SSD > 2GB Video",
    availability_circle_origin: "",
  },
  {
    id: "CPU-I5-9G-T",
    title: "CPU Tiny Intel Core i5 9na Gen (8GB RAM / 256GB SSD)",
    colection: "",
    valery_name: "CPU i5 9na Gen 8RAM 256SSD TINY",
    description:
      "• Procesador de 9na generación para máxima compatibilidad y velocidad. • Formato Tiny profesional. • SSD optimizado para carga rápida de aplicaciones.",
    availability: "in stock",
    condition: "refurbished",
    price: 300,
    link: "https://wa.me/584129230341?text=Hola%20Compucentro,%20me%20interesa%20el%20producto%20ID:%20CPU-I5-9G-T%20-%20CPU Tiny Intel Core i5 9na Gen (8GB RAM / 256GB SSD)",
    image_link:
      "https://raw.githubusercontent.com/KDR-2/compucentro-img/main/CPU-I5-9G-T.webp",
    additional_image_link: "",
    brand: "HP / Dell / Lenovo",
    google_product_category: 222,
    product_type:
      "Computadoras > Desktops > Tiny > i5 > 9na Gen > 8GB RAM > 256GB SSD",
    availability_circle_origin: "",
  },
  {
    id: "CPU-I5-8G-T",
    title: "CPU Tiny Intel Core i5 8va Gen (8GB RAM / 256GB SSD)",
    colection: "",
    valery_name: "CPU i5 8va Gen 8RAM 256SSD TINY",
    description:
      "• Estación de trabajo compacta y confiable. • Perfecta para tareas administrativas y streaming. • Almacenamiento sólido incluido.",
    availability: "in stock",
    condition: "refurbished",
    price: 240,
    link: "https://wa.me/584129230341?text=Hola%20Compucentro,%20me%20interesa%20el%20producto%20ID:%20CPU-I5-8G-T%20-%20CPU Tiny Intel Core i5 8va Gen (8GB RAM / 256GB SSD)",
    image_link:
      "https://raw.githubusercontent.com/KDR-2/compucentro-img/main/CPU-I5-8G-T.webp",
    additional_image_link: "",
    brand: "HP / Dell / Lenovo",
    google_product_category: 222,
    product_type:
      "Computadoras > Desktops > Tiny > i5 > 8va Gen > 8GB RAM > 256GB SSD",
    availability_circle_origin: "",
  },
  {
    id: "CPU-I5-7G-T",
    title: "CPU Tiny Intel Core i5 7ma Gen (8GB RAM / 256GB SSD)",
    colection: "",
    valery_name: "CPU i5 7ma Gen 8RAM 256SSD TINY",
    description:
      "• Estación de trabajo ultra compacta de alto rendimiento. • Disco sólido SSD de 256GB para velocidad en todas tus tareas. • Diseño Tiny ideal para optimizar espacios de oficina.",
    availability: "in stock",
    condition: "refurbished",
    price: 210,
    link: "https://wa.me/584129230341?text=Hola%20Compucentro,%20me%20interesa%20el%20producto%20ID:%20CPU-I5-7G-T%20-%20CPU Tiny Intel Core i5 7ma Gen (8GB RAM / 256GB SSD)",
    image_link:
      "https://raw.githubusercontent.com/KDR-2/compucentro-img/main/CPU-I5-7G-T.webp",
    additional_image_link: "",
    brand: "HP / Dell / Lenovo",
    google_product_category: 222,
    product_type:
      "Computadoras > Desktops > Tiny > i5 > 7ma Gen > 8GB RAM > 256GB SSD",
    availability_circle_origin: "",
  },
  {
    id: "CPU-I3-9G-T",
    title: "CPU Tiny Intel Core i3 9na Gen (8GB RAM / 256GB SSD)",
    colection: "",
    valery_name: "CPU i3 9na Gen 8RAM 256SSD TINY",
    description:
      "• Tecnología de 9na generación a precio accesible. • Formato ultra pequeño de bajo consumo. • Ideal para estudios y oficina básica.",
    availability: "in stock",
    condition: "refurbished",
    price: 232.5,
    link: "https://wa.me/584129230341?text=Hola%20Compucentro,%20me%20interesa%20el%20producto%20ID:%20CPU-I3-9G-T%20-%20CPU Tiny Intel Core i3 9na Gen (8GB RAM / 256GB SSD)",
    image_link:
      "https://raw.githubusercontent.com/KDR-2/compucentro-img/main/CPU-I3-9G-T.webp",
    additional_image_link: "",
    brand: "HP / Dell / Lenovo",
    google_product_category: 222,
    product_type:
      "Computadoras > Desktops > Tiny > i3 > 9na Gen > 8GB RAM > 256GB SSD",
    availability_circle_origin: "",
  },
  {
    id: "CPU-I7-4G-U",
    title: "CPU USFF Intel Core i7 4ta Gen (4GB RAM / 128GB SSD)",
    colection: "",
    valery_name: "CPU i7 4ta Gen 4RAM 128SSD USFF",
    description:
      "• Formato USFF robusto y duradero. • Potencia i7 clásica para tareas de alta demanda. • SSD de 128GB para un encendido en segundos.",
    availability: "out of stock",
    condition: "refurbished",
    price: 180,
    link: "https://wa.me/584129230341?text=Hola%20Compucentro,%20me%20interesa%20el%20producto%20ID:%20CPU-I7-4G-U%20-%20CPU USFF Intel Core i7 4ta Gen (4GB RAM / 128GB SSD)",
    image_link:
      "https://raw.githubusercontent.com/KDR-2/compucentro-img/main/CPU-I7-4G-U.webp",
    additional_image_link: "",
    brand: "HP / Dell / Lenovo",
    google_product_category: 222,
    product_type:
      "Computadoras > Desktops > USFF > i7 > 4ta Gen > 4GB RAM > 128GB SSD",
    availability_circle_origin: "",
  },
  {
    id: "CPU-I5-4G-U",
    title: "CPU USFF Intel Core i5 4ta Gen (4GB RAM / 128GB SSD)",
    colection: "",
    valery_name: "CPU i5 4ta Gen 4RAM 128SSD USFF",
    description:
      "• El balance perfecto para puntos de venta o administración. • Chasis USFF resistente. • Rendimiento fluido con tecnología SSD.",
    availability: "in stock",
    condition: "refurbished",
    price: 127.5,
    link: "https://wa.me/584129230341?text=Hola%20Compucentro,%20me%20interesa%20el%20producto%20ID:%20CPU-I5-4G-U%20-%20CPU USFF Intel Core i5 4ta Gen (4GB RAM / 128GB SSD)",
    image_link:
      "https://raw.githubusercontent.com/KDR-2/compucentro-img/main/CPU-I5-4G-U.webp",
    additional_image_link: "",
    brand: "HP / Dell / Lenovo",
    google_product_category: 222,
    product_type:
      "Computadoras > Desktops > USFF > i5 > 4ta Gen > 4GB RAM > 128GB SSD",
    availability_circle_origin: "",
  },
  {
    id: "CPU-I5-3G-U",
    title: "CPU USFF Intel Core i5 3ra Gen (4GB RAM / 240GB SSD)",
    colection: "",
    valery_name: "CPU i5 3ra Gen 4RAM 240SSD USFF",
    description:
      "• Almacenamiento ampliado de 240GB SSD. • Excelente opción económica para el hogar. • Formato compacto y fácil de ubicar.",
    availability: "in stock",
    condition: "refurbished",
    price: 127.5,
    link: "https://wa.me/584129230341?text=Hola%20Compucentro,%20me%20interesa%20el%20producto%20ID:%20CPU-I5-3G-U%20-%20CPU USFF Intel Core i5 3ra Gen (4GB RAM / 240GB SSD)",
    image_link:
      "https://raw.githubusercontent.com/KDR-2/compucentro-img/main/CPU-I5-3G-U.webp",
    additional_image_link: "",
    brand: "HP / Dell / Lenovo",
    google_product_category: 222,
    product_type:
      "Computadoras > Desktops > USFF > i5 > 3ra Gen > 4GB RAM > 240GB SSD",
    availability_circle_origin: "",
  },
  {
    id: "",
    title: "",
    colection: "",
    valery_name: "",
    description: "",
    availability: "",
    condition: "",
    price: "",
    link: "",
    image_link: "",
    additional_image_link: "",
    brand: "",
    google_product_category: "",
    product_type: "",
    availability_circle_origin: "",
  },
  {
    id: "ACC-CTRL-SNES",
    title: "Control Super Nintendo Genérico",
    colection: "",
    valery_name: "Control Super Nintendo",
    description:
      "🔹 Tipo: Mando de juego clásico \\n🔹 Compatibilidad: Super Nintendo / Adaptadores \\n🔹 Diseño: Ergonómico retro \\n🔹 Equipo renovado♻️ con 6 meses de garantía \\n💵 Ofrecemos precio al mayor disponible en divisas",
    availability: "in stock",
    condition: "refurbished",
    price: "",
    link: "",
    image_link: "[URL_IMAGEN]",
    additional_image_link: "",
    brand: "",
    google_product_category: "Accesorios > Controles > Retro",
    product_type: "Video Game Console Accessories",
    availability_circle_origin: "",
  },
  {
    id: "ACC-CORN-GEN",
    title: "Cornetas de Sonido Estéreo",
    colection: "",
    valery_name: "Cornetas",
    description:
      "🔹 Tipo: Periférico de salida de audio \\n🔹 Conexión: Plug 3.5mm / USB \\n🔹 Uso: PC / Laptop / Tablet \\n🔹 Equipo renovado♻️ con 6 meses de garantía \\n💵 Ofrecemos precio al mayor disponible en divisas",
    availability: "in stock",
    condition: "refurbished",
    price: "",
    link: "",
    image_link: "[URL_IMAGEN]",
    additional_image_link: "",
    brand: "",
    google_product_category: "Accesorios > Audio > Cornetas",
    product_type: "Electronics > Audio > Audio Components > Speakers",
    availability_circle_origin: "",
  },
  {
    id: "CPU-I3-8G-8-250",
    title: "CPU i3 8va Gen 8GB RAM 250GB SSD",
    colection: "",
    valery_name: "CPU i3 8va Gen 8RAM 250SSD",
    description:
      "🔹 Procesador: Intel Core i3 8va Gen (4 Núcleos / 4 Hilos) \\n🔹 Gráficos: Intel UHD Graphics 630 \\n🔹 Memoria RAM: 8GB DDR4 - Expandible! \\n🔹 Almacenamiento: 250GB SSD \\n🔹 Sistema operativo: Windows 11 \\n🔹 Paquete Office: Instalado \\n🔹 Equipo renovado♻️ con 6 meses de garantía \\n💵 Ofrecemos precio al mayor disponible en divisas",
    availability: "in stock",
    condition: "refurbished",
    price: "",
    link: "",
    image_link: "[URL_IMAGEN]",
    additional_image_link: "",
    brand: "",
    google_product_category:
      "Computadoras > CPU > i3 > 8va Gen > 8RAM > 250SSD",
    product_type: "Electronics > Computers > Desktop Computers",
    availability_circle_origin: "",
  },
];
